[package]

name = "janeiro"
version = "0.0.1"
authors = [ "Guillaume Gauvrit <guillaume@gauvr.it>" ]

[[bin]]

name = "janeiro"


[dependencies]
log   = "0.3.1"
env_logger = "0.3.1"
mio =  { git = "https://github.com/carllerche/mio" }
nix = "0.4.1"
net2 = "0.2.15"
