[package]

name = "janeiro"
version = "0.0.1"
authors = [ "Guillaume Gauvrit <guillaume@gauvr.it>" ]


[dependencies]
log   = "0.3.6"
env_logger = "0.3.5"
mio =  "0.6.1"
slab = "0.3.0"
nix = "0.7.0"
net2 = "0.2.26"

[dev-dependencies]
env_logger = "0.3.5"
